# 3-Hour Training Configuration for GRPO
# This config provides longer training (~3 hours) with more data and epochs
# Target: ~375 steps total, ~1 step/minute = ~3 hours

experiment_name: gsm8k-grpo-3hour
trial_name: trial0

# Training configuration
max_train_samples: 1000  # Limit dataset to 1000 samples for ~3 hour training
training_mode: "3-HOUR"
circuit_breaker_enabled: true
circuit_breaker_threshold: 10

seed: 1
total_train_epochs: 3  # 3 epochs for better convergence
tokenizer_path: ${actor.path}
async_training: true

cluster:
  n_nodes: 1
  n_gpus_per_node: 1
  fileroot: ./outputs/grpo
  name_resolve:
    type: nfs
    nfs_record_root: ./tmp/areal/name_resolve

allocation_mode: sglang.d1p1t1+d1p1t1

rollout:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  max_concurrent_rollouts: 32
  queue_size: null
  consumer_batch_size: ${train_dataset.batch_size}
  max_head_offpolicyness: 2
  enable_rollout_tracing: false

gconfig:
  n_samples: 4  # Keep 4 samples for better GRPO quality
  min_new_tokens: 0
  max_new_tokens: 512  # Keep full length for better reasoning
  greedy: false
  temperature: 1.0

actor:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  path: Qwen/Qwen2.5-0.5B-Instruct
  init_from_scratch: false
  disable_dropout: true
  gradient_checkpointing: false
  dtype: bfloat16
  mb_spec:
    max_tokens_per_mb: 5120
  optimizer:
    type: adam
    lr: 1.70e-5
    weight_decay: 0.017
    beta1: 0.9
    beta2: 0.999
    eps: 1e-8
    lr_scheduler_type: constant
    gradient_clipping: 1.0
    warmup_steps_proportion: 0.001
  backend: fsdp
  group_size: ${gconfig.n_samples}  # 4 samples per group
  eps_clip: 0.4
  temperature: ${gconfig.temperature}
  reward_scaling: 10.0
  reward_bias: -0.5
  kl_ctl: 0.0
  ppo_n_minibatches: 1
  recompute_logprob: true
  use_decoupled_loss: true
  behav_imp_weight_cap: 5.0
  dynamic_sampling: false
  reward_norm:
    mean_level: group
    std_level: group
    group_size: ${gconfig.n_samples}
  adv_norm:
    mean_level: batch
    std_level: batch
  max_new_tokens: ${gconfig.max_new_tokens}

ref:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  path: ${actor.path}
  init_from_scratch: false
  disable_dropout: true
  dtype: ${actor.dtype}
  mb_spec:
    max_tokens_per_mb: 5120
  optimizer: null
  backend: fsdp

# SGLang
sglang:
  model_path: ${actor.path}
  random_seed: ${seed}
  skip_tokenizer_init: true
  dtype: ${actor.dtype}
  max_running_requests: null
  context_length: 4096
  mem_fraction_static: 0.8

# datasets
train_dataset:
  batch_size: 8  # Keep batch_size=8 for stability
  shuffle: true
  pin_memory: true
  num_workers: 0
  path: openai/gsm8k
  type: rl
  max_length: 512
  # Note: Dataset size will be limited to ~1000 samples in the training script
  # This gives: 1000 / 8 = ~125 steps per epoch
  # With 3 epochs: ~375 steps total
  # At ~1 step/min: ~3 hours

valid_dataset:
  batch_size: 8
  shuffle: true
  pin_memory: true
  num_workers: 0
  path: openai/gsm8k
  type: rl
  max_length: 512

# Utilities
saver:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1  # Save after each epoch
  freq_steps: null
  freq_secs: null

recover:
  mode: disabled
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: null
  freq_secs: 3600

evaluator:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1  # Evaluate after each epoch
  freq_steps: null
  freq_secs: null

stats_logger:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  wandb:
    mode: online
    wandb_api_key: ${oc.env:WANDB_API_KEY}
    project: gsm8k-grpo-local

launcher:
  inference_server_cpus_per_gpu: 4
  inference_server_mem_per_gpu: 16384
  trainer_cpus_per_gpu: 4
  trainer_mem_per_gpu: 16384

